stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375

test:
  stage: test
  image: docker:stable
  services:
  - name: docker:dind
    command: ["--tls=false"]

  variables: 
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    #- pip install poetry
    #- cd app
    #- poetry config virtualenvs.create false && poetry install
    - sleep 30 && export DOCKER_HOST=tcp://localhost:2375 && docker build --pull -t my_fastapi .
    - docker-compose up -d
    - pytest tests
    - docker-compose down
