stages:
  - test

variables:
  DOCKER_HOST: tcp://localhost:2375

test:
  stage: test
  image: docker:stable
  services:
  - name: docker:19-dind
    command: ["--tls=false"]

  variables: 
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    #- pip install poetry
    #- cd app
    #- poetry config virtualenvs.create false && poetry install
    - while ! nc -z localhost 2375; do sleep 0.1; done # Wait until docker socket is available
    - docker build --pull -t my_fastapi .
    - docker-compose up -d
    - pytest tests
    - docker-compose down
