stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375

test:
  stage: test
  image:
      name: docker/compose:latest
      entrypoint: ["/bin/sh", "-c"]
  services:
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh", "--tls=false"]
  

  #variables: 
  #  DOCKER_TLS_CERTDIR: "/certs"
  script:
    #- pip install poetry
    #- cd app
    #- poetry config virtualenvs.create false && poetry install
    - export DOCKER_HOST=tcp://docker:2375 && docker build -t my_fastapi -f dockerfile .
    - docker-compose up -d
    - docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' Users_Service
    - docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres
    - sleep 5
    - docker exec Users_Service pytest tests
    - docker-compose down
