stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375

test:
  stage: test
  image: docker:20.10.18
  services:
    - docker:20.10.18-dind
  variables: 
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    #- pip install poetry
    #- cd app
    #- poetry config virtualenvs.create false && poetry install
    - docker build -t my_fastapi -f dockerfile .
    - docker-compose up -d
    - pytest tests
    - docker-compose down
