stages:
  - test

test:
  stage: test
  image:
      name: docker/compose:latest
      entrypoint: ["/bin/sh", "-c"]
  script:
    #- pip install poetry
    #- cd app
    #- poetry config virtualenvs.create false && poetry install
    - docker build -t my_fastapi -f Dockerfile .
    - docker-compose up -d
    - pytest tests
    - docker-compose down
