stages:
  - test

test:
  stage: test
  image: python:latest
  script:
    #- pip install poetry
    #- cd app
    #- poetry config virtualenvs.create false && poetry install
    - docker-compose up -d
    - pytest tests
    - docker-compose down
