stages:
  - docker_build
  - test

docker_build:
  stage: docker_build
  script:
    - docker pull postgres
    - docker-compose up

test:
  stage: test
  image: python:latest
  script:
    - pip install poetry
    - cd app
    - poetry config virtualenvs.create false && poetry install
    - pytest tests
    - docker-compose down
