version: "3"
services:
  Users:
    container_name: Users_Service
    command: bash -c 'while !</dev/tcp/docker/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 80'
    image: my_fastapi
    build: 
      dockerfile: Dockerfile
    depends_on:
      - Postgres
#      Postgres:
#        condition: service_healthy
    networks:
      - my_network
    ports:
      - "8000:80"
    links:
      - Postgres
      
  Postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    networks:
      - my_network
    ports:
      - "5432:5432"
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -U postgres"]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 5

  #PGAdmin:
  #  container_name: pgadmin
  #  image: dpage/pgadmin4
  #  restart: always
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: root@root.com
  #    PGADMIN_DEFAULT_PASSWORD: pass
  #  networks:
  #    - my_network
  #  ports:
  #    - "5050:80"
networks:
  my_network:
    name: my_network
    driver: bridge