version: "3"
services:
  Users:
    container_name: Users_Service
    command: bash -c 'while !</dev/tcp/Postgres/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 80'
    image: my_fastapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - Postgres
      - Redis
    networks:
      - my_network
    ports:
      - "8000:80"
    links:
      - Postgres
      
  Postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - my_network
    ports:
      - "5432:5432"

  Redis:
    container_name: redis
    image: redis
    restart: always
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks: 
      - my_network
    ports:
      - "6379:6379"
    
  Rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
        - 15672:15672
        - 5672:5672
    networks:
        - my_network

  #PGAdmin:
  #  container_name: pgadmin
  #  image: dpage/pgadmin4
  #  restart: always
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: root@root.com
  #    PGADMIN_DEFAULT_PASSWORD: pass
  #  networks:
  #    - my_network
  #  ports:
  #    - "5050:80"

networks:
  my_network:
    driver: bridge